name: LaZerGun
main: net.ddns.vcccd.Main
version: 1.0.3
api-version: 1.20
commands:
   lazergun:
      description: Gives you the LaZerGun
      usage: /<command>
      permission: lazergun.give
   superlazergun:
      description: Gives you the LaZerGun
      usage: /<command>
      permission: lazergun.give